name: CI - Test with RabbitMQ

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          rabbitmqctl add_vhost my_vhost
          rabbitmqctl set_permissions -p my_vhost guest ".*" ".*" ".*"

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        AMQP_ADDR: amqp://guest:guest@localhost:5672/my_vhost
